### ISSUE TITLE
SelectionBox component fairly broken

### ISSUE THREAD

**Issue by InvexGames** [InvexGames/MaterialUI#9]
Just thought I'd let you guys know, I'll fix it when I can.

So far I've noticed the 'highlight last selected' and 'expand direction' options don't work as they should.

**Comment by InvexGames** [comment]
Fixed now.

**Comment by nah0y** [comment]
There is still an issue (if I may :D).
If the selectionBox is child of a gameobject, and that you move this gameObject at runtime. Everything is broken.

So for example a selectionBox is child of a panel. You press play, move the panel (when in play mode), then click on the selectionBox, you'll see everything is broken ;)

**Comment by InvexGames** [comment]
Oh dear. I'll get right on that.

**Comment by InvexGames** [comment]
Okay. It seemed to be that it cached the base position on start, so if it was moved it was still using the old position. I changed it so it updates that position every time you expand it. So as long as it's not moving *while* it's expanding/contracting, it'll work just fine. Do you think it should be changed so that it can be moved while being interacted with?

**Comment by InvexGames** [comment]
Alrighty. Fixed now.

**Comment by nah0y** [comment]
Hehe :)
I don't know, I think that it's enough (at least for me, for now :D) but we never know how people will use the app... so maybe some will expand it while moving, I don't know :p

**Comment by InvexGames** [comment]
I decided to play it safe and fix it anyway. You can now move it whenever :)

**Comment by nah0y** [comment]
You're great :)
